### PR TITLE
Fix CellularInterface functions never being defined

### PR DESCRIPTION
**Pull request by multiplemonomials**
### Summary of changes 

In Mbed CE, the `MBED_CONF_CELLULAR_PRESENT` define is defined only by linking to the `mbed-cellular` library (compared to old Mbed OS, where it was defined globally for the entire OS, which was... not good).  NetworkInterfaceDefaults.cpp tried to use this define, but it's likely to be undefined there, since mbed-cellular is not guaranteed to be linked to this library.

This PR moves this function to `mbed-cellular`, where MBED_CONF_CELLULAR_PRESENT is guaranteed to be defined.  This fixes the "Undefined reference to vtable for CellularInterface" link error that it was possible to get.

NOTE: Even after this PR, `mbed-cellular` may still fail to link with an undefined reference due to #304.  That issue has its own workaround, check there for details.

### Documentation 

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [X] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [X] Tests / results supplied as part of this PR

With the workaround for #304 plus this patch, I can now successfully link a program that uses mbed-cellular!    
    
----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

File: connectivity/netsocket/CMakeLists.txt [hunk 1]
```diff
@@ -64,6 +64,11 @@ elseif("MBED_CONF_NSAPI_DEFAULT_STACK=NANOSTACK" IN_LIST MBED_CONFIG_DEFINITIONS
     target_link_libraries(mbed-netsocket-api PUBLIC mbed-nanostack)
 endif()
 
+# Pull in cellular if cellular is the default network interface (used by NetworkInterfaceDefaults.cpp)
```
Comment (multiplemonomials) [inline connectivity/netsocket/CMakeLists.txt:67]: This block is required for another part of NetworkInterfaceDefaults.cpp to work, because that block need to have access to `mbed-cellular` functions if cellular is the default network interface.

File: connectivity/netsocket/source/NetworkInterfaceDefaults.cpp [hunk 2]
```diff
@@ -43,13 +43,6 @@ MBED_WEAK MeshInterface *MeshInterface::get_default_instance()
     return get_target_default_instance();
 }
 
-#if MBED_CONF_CELLULAR_PRESENT
```
Comment (multiplemonomials) [inline connectivity/netsocket/source/NetworkInterfaceDefaults.cpp:46]: Since cellular drivers are now compiled as a .a static library, and the linker does not resolve weak symbols between .a libraries, making this function weak does not actually work -- it will not get reliably overridden.  It's better to delete it and require the application or a driver to define it.

**Review by JohnK1987 — APPROVED** [review]
